defaultSource: "file"           # for import of data
# file types that are allowed for import from Pandora ("ckan")
ckanFileTypes:
  - "zipm"
  - "zip"
fileExtension: "zipm"   # for import of models
rPackageName: "MapR"
