defaultSource: "file"           # for import of data
# file types that are allowed for import from Pandora ("ckan")
ckanFileTypes:
  - "mapr"
  - "zip"
defaultFileName: "mapR_session" # for download of user inputs
fileExtension: "mapr"   # for import of models
rPackageName: "MapR"
